name: Docker build (ubuntu runner)

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Show python version
        run: python3 --version

      - name: Build Docker image
        run: |
          docker build -t ocr-api:ci .

      - name: Show image info
        run: docker image inspect ocr-api:ci || true

      - name: List layers size
        run: docker history --no-trunc ocr-api:ci | head -n 20 || true

